from typing import List, Optional, Tuple
from pydantic import BaseModel, Field


class TextChunk(BaseModel):
    text: str = Field(..., alias="chunk", description="The chunked text content.")
    line_span: Tuple[int, int] = Field(
        ...,
        description="Inclusive 1-based (start_line, end_line) in the source file.",
        examples=[(12, 24)],
    )
    source_file: str = Field(
        ...,
        description="Path to the file from which the chunk was extracted.",
    )
    routing_key: Optional[str] = Field(
        default=None,
        description="Routing key for agent processing"
    )

class LineComment(BaseModel):
    line_number: int = Field(..., description="Line number in the file (1-based).")
    comment: str = Field(..., description="Reviewer comment for this line.")

class SecretsDetectorExecutorResponse(BaseModel):
    comments: List[LineComment] = Field(
        default_factory=list,
        description="All line-level comments generated by the detector.",
    )
    original_file: str = Field(
        ...,
        alias="original_file",
        description="Path to the original file that was scanned.",
    )
    executor_agent: str = Field(
        default="No agent",
        description="The id of the executor agent who processed this request",
    )